### ISSUE TITLE
Insane API tracking issue

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh-ffi#53]
Tracking issue for parity with the entire Iroh API (with a few exceptions, specifically methods that take a stream or reader as an input).

### iroh client
- [x]  `node.stats`
 ```
/// Get statistics of the running node.
pub fn node_stats(&self) -> Result<HashMap<String, CounterStats>, IrohError>
```
- [x] `node.connections`
```
/// Get information about the different connections we have made
/// Note: this allocates for each `ConnectioInfo`, if you have many `ConnectionInfo`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn node_connections(&self) -> Result<Vec<ConnectionInfo>, IrohError>
```
- [x] `node.connection_info`
```
/// Get connection information about a node
pub fn node_connection_info(&self, node_id: PublicKey) -> Result<Option<ConnectionInfo>, IrohError>
```
- [x] `node.status`
```
/// Get status information about a node
pub fn node_status(&self) -> Result<NodeStatusResponse, IrohError>
```
- [x] `node.shutdown` 
```
/// Shutdown the node.
/// If `force` is true, the node will be killed instantly without waiting for things to
/// shutdown gracefully.
pub fn node_shutdown(&self, force: bool) -> Result<(), IrohError> 
```
- [x] `docs.create` 
```
/// Create a new document.
pub fn docs_create(&self) -> Result<Doc, IrohError>
```
- [x] `docs.delete`
```
/// Delete a document from the local node.
///
/// This is a destructive operation. Both the document secret key and all entries in the
/// document will be permanently deleted from the node's storage. Content blobs will be deleted
/// through garbage collection unless they are referenced from another document or tag.
pub fn docs_drop_doc(&self, doc_id: NamespaceId) -> Result<(), IrohError>
```
- [x] `docs.import`
```
 /// Import a document from a ticket and join all peers in the ticket.
 pub fn docs_import(&self, ticket: DocTicket) -> Result<Doc, IrohError>
```
- [x] `docs.list`
```
/// List all documents.
pub fn docs_list(&self) -> Result<Vec<NamespaceId>, IrohError>
``` 
- [x] `docs.open`
```
/// Get a [`Doc`] client for a single document. Return None if the document cannot be found.
pub fn docs_open(&self, id: NamespaceId) -> Result<Option<Doc>, IrohError>
```
- [x] `authors.create`
```
/// Create a new document author.
pub fn authors_create(&self) -> Result<AuthorId, IrohError>
```
- [x] `authors.list`
```
/// List document authors for which we have a secret key.
///
/// Note: this allocates for each `AuthorId`, if you have many `AuthorId`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn authors_list(&self) -> Result<Vec<AuthorId>, IrohError>
``` 
- [x] `tags.list`
```
/// List all tags.
/// Note: this allocates for each `ListTagsResponse`, if you have many `Tags`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn tags_list(&self) -> Result<ListTagsResponse, IrohError> 
```
- [x] `tags.delete`
```
/// Delete a tag.
pub fn tags_delete(&self, name: Tag) -> Result<(), IrohError>
```

- [x] `blobs_size` **FFI METHOD ONLY**
```
/// Get the size information on a single blob.
///
pub fn blobs_size(&self, hash: Hash) -> Result<u64, IrohError>
```

- [x] `blobs_write_to_path` **FFI METHOD ONLY**
```
/// Export the blob contents to a file path
/// The `path` field is expected to be the absolute path.
pub fn blobs_write_to_path(&self, hash: Hash, path: String) -> Result<(), IrohError>
```

- [x] `blobs.read_to_bytes`
```
/// Read all bytes of single blob.
///
/// This allocates a buffer for the full blob. Use only if you know that the blob you're
/// reading is small. If not sure, use [`Self::blobs_size`] and check the size with
/// before calling [`Self::blobs_read_to_bytes`].
pub fn blobs_read_to_bytes(&self, hash: Hash) -> Result<Vec<u8>, IrohError>
```

- [x] `blobs.add_from_path`
```
/// Import a blob from a filesystem path.
///
/// `path` should be an absolute path valid for the file system on which
/// the node runs.
/// If `in_place` is true, Iroh will assume that the data will not change and will share it in
/// place without copying to the Iroh data directory.
pub fn blobs_add_from_path(
        &self,
        path: PathBuf,
        in_place: bool,
        tag: SetTagOption,
        wrap: WrapOption,
        cb: Box<dyn AddCallback>
) -> Result<(), IrohError>
```

- [x] `blobs.add_bytes`
```
    /// Write a blob by passing bytes.
    pub fn blobs_add_bytes(
        &self,
        bytes: Vec<u8>,
        tag: SetTagOption,
    ) -> Result<BlobAddOutcome, IrohError>
```

- ~`blobs.validate`~ Not implemented in core
```
/// Validate hashes on the running node.
///
/// If `repair` is true, repair the store by removing invalid data.
pub fn blobs_validate(
        &self,
        repair: bool,
        cb: Box<dyn ValidateCallback>
 ) -> Result<(), IrohError>
```

- [x] `blobs.download`
```
/// Download a blob from another node and add it to the local database.
pub fn blobs_download(
        &self,
        req: BlobDownloadRequest,
        cb: Box<dyn DownloadCallback>
) -> Result<(), IrohError>
```

- [x] `blobs.list`
```
/// List all complete blobs.
///
/// Note: this allocates for each `BlobListResponse`, if you have many `BlobListReponse`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn blobs_list(&self) -> Result<Vec<BlobListResponse>, IrohError>
```

- [x] `blobs.list_incomplete`
```
/// List all incomplete (partial) blobs.
///
/// Note: this allocates for each `BlobListIncompleteResponse`, if you have many `BlobListIncompleteResponse`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn blobs_list_incomplete(
        &self,
) -> Result<Vec<BlobListIncompleteResponse>, IrohError>
```

- [x] `blobs.list_collections`
```
/// List all collections.
///
/// Note: this allocates for each `BlobListCollectionsResponse`, if you have many `BlobListCollectionsResponse`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn blobs_list_collections(
        &self,
) -> Result<Vec<BlobListCollectionsResponse>, IrohError>
```

- [x] `blobs.delete_blob`
```
/// Delete a blob.
pub fn blobs_delete_blob(&self, hash: Hash) -> Result<(), IrohError>
```

### structs and enums
- [x] `struct Doc` - interface
```
pub struct Doc(Doc);

impl Doc {
/// Get the document id of this doc.
pub fn id(&self) -> Arc<NamespaceId>

/// Close the document.
pub fn close(&self) -> Result<(), IrohError>

/// Set the content of a key to a byte array.
pub fn set_bytes(
        &self,
        author_id: AuthorId,
        key: Vec<u8>,
        value: Vec<u8>,
) -> Result<Arc<Hash>, IrohError>

/// Set an entries on the doc via its key, hash, and size.
pub fn set_hash(
        &self,
        author_id: AuthorId,
        key: Vec<u8>,
        hash: Hash,
        size: u64,
) -> Result<(), IrohError>

/// Get the content size of an [`Entry`]
pub fn size(&self, entry: &Entry) -> Result<u64, IrohError>

/// Read all content of an [`Entry`] into a buffer.
/// This allocates a buffer for the full entry. Use only if you know that the entry you're
/// reading is small. If not sure, use [`Self::size`] and check the size with
/// before calling [`Self::read_to_bytes`].

pub fn read_to_bytes(&self, entry: &Entry) -> Result<Vec<u8>, IrohError>

/// Delete entries that match the given `author` and key `prefix`.
///
/// This inserts an empty entry with the key set to `prefix`, effectively clearing all other
/// entries whose key starts with or is equal to the given `prefix`.
///
/// Returns the number of entries deleted.
pub fn del(&self, author_id: AuthorId, prefix: Vec<u8>) -> Result<usize, IrohError>

/// Get the latest entry for a key and author.
pub fn get_one(&self, author: AuthorId, key: Vec<u8>) -> Result<Option<Entry>, IrohError>

/// Get entries.
///
/// Note: this allocates for each `Entry`, if you have many `Entry`s this may be a prohibitively large list.
/// Please file an [issue](https://github.com/n0-computer/iroh-ffi/issues/new) if you run into this issue
pub fn get_many(&self, filter: GetFilter) -> Result<Vec<Arc<Entry>>, IrohError>

/// Share this document with peers over a ticket.
pub fn share(&self, mode: ShareMode) -> anyhow::Result<Arc<DocTicket>, IrohError>

/// Start to sync this document with a list of peers.
pub fn start_sync(&self, peers: Vec<PeerAddr>) -> Result<(), IrohError>

/// Stop the live sync for this document.
pub fn leave(&self) -> Result<(), IrohError>

/// Subscribe to events for this document.
pub fn subscribe(&self, cb: Box<dyn SubscribeCallback>) -> Result<(), IrohError>

/// Get status info for this document
pub fn status(&self) -> Result<Arc<OpenState>, IrohError>
```

- [x] `struct CounterStats` - interface
```
/// Counter stats
pub struct CounterStats (CounterStats);
impl CounterStats {
    /// The counter value
    pub fn value(&self) -> u64
    /// The counter description
    pub fn description(&self) -> String
}
```

- [x] `struct ConnectionInfo` - interface
```
/// Details about an Endpoint
pub struct ConnectionInfo(EndpointInfo); {

impl ConnectionInfo {
    /// The public key of the peer
    pub fn public_key(&self) -> Arc<PublicKey>
    /// The derp region of the peer
    pub fn derp_region(&self) -> Option<u16>
    /// The addrs of the peer
    pub fn addrs(&self) -> Arc<DirectAddrInfo>
    /// The type of connection we have to that peer
    pub fn conn_type(&self) -> Arc<ConnectionKind>
    /// The latency of the [`ConnectionKind`]
    pub fn latency(&self) -> Option<Duration>
    /// The duration since the last time this peer was used
    pub fn last_used(&self) -> Option<Duration>
}
```

- [x] `struct DirectAddrInfo` - interface
```
/// Information about a direct address
pub struct DirectAddrInfo(DirectAddrInfo);

impl DirectAddrInfo {
    /// The `SocketAddr` of the peer
    pub fn addr(&self) -> Arc<SocketAddr>
    /// The latency to the address, if any
    pub fn latency(&self) -> Option<Duration>
    /// Last control message received by this peer
    pub fn last_control(&self) -> Option<(Duration, ControlMsg)>
    /// How long ago was the last payload message for this peer
    pub last_payload(&self) -> Option<Duration>
}
```

- [ ] `enum ControlMsg` - enum
```
/// Type of control message we have received from the peer
pub enum ControlMsg {
    /// We received a Ping from the peer
    Ping,
    /// We received a Pong from the peer
    Pong,
    /// We received a CallMeMaybe from the peer
    CallMeMaybe
}
```

- [x] `enum ConnectionType` - interface
```
/// The kind of Connection we have to the peer
pub enum ConnectionType {
    /// Direct UDP connection
    Direct(SocketAddr),
    /// Relay connection over DERP
    Relay(u16),
    /// We have no verified connection to this PublicKey
    None
}

/// The type of ConnectionType
pub enum ConnType {
    Direct,
    Relay,
    None
}

impl ConnectionType {
    /// Whether the connection is direct, a relay, or unverified (aka none)
    pub fn r#type(&self) -> ConnType

    /// Return the [`SocketAddr`] if this is a direct connection
    pub fn as_direct(&self) -> Result<SocketAddr, IrohError>

    /// Return the derp region id if this is a relay connection 
    pub fn as_relay(&self) -> Result<u16, IrohError>
}
```

- [x] `struct NodeStatusResponse` - interface
```
/// The response to a version request
pub struct NodeStatusResponse(NodeStatusResponse)
impl NodeStatusResponse {
    /// The peer id and socket addresses of this node.
    pub fn peer_addr(&self) -> Arc<PeerAddr>
    /// The bound listening addresses of the node
    pub fn listen_addrs(&self) -> Vec<Arc<SocketAddr>>
    /// The version of the node
    pub fn version(&self) -> String
}
```

- [x] `ListTagsResponse` - interface
```
/// A response to a list collections request
pub struct ListTagsResponse (ListTagsResponse)
impl ListTagsResponse {
    /// Name of the tag
    pub fn name(&self) -> Arc<Tag>
    /// Format of the data
    pub fn format(&self) -> BlobFormat
    /// Hash of the data
    pub fn hash(&self) -> Arc<Hash>
}
```

- [x] `SetTagOption` - interface
```
pub enum SetTagOption {
    /// A tag will be automatically generated
    Auto,
    /// The tag is explicitly named
    Named(Tag),
}

impl SetTagOption {
    /// Indicate you want an automatically generated tag
    pub fn auto() -> Self
    /// Indicate you want a named tag
    pub fn named(tag: Tag) -> Self
}
```

- [x] `WrapOption` - interface
```
/// Whether to wrap the added data in a collection.
pub enum WrapOption {
    /// Do not wrap the file or directory.
    NoWrap,
    /// Wrap the file or directory in a colletion.
    Wrap {
        /// Override the filename in the wrapping collection.
        name: Option<String>,
    },
}

impl WrapOption {
    /// Indicate you do not wrap the file or directory.
    pub fn no_wrap() -> Self

    /// Indicate you want to wrap the file or directory in a colletion, with an
    optional name
    pub fn wrap(name: Option<String>) -> Self
}
```

- [x] `BlobAddOutcome` - dictionary
```
/// Outcome of a blob add operation.
pub struct BlobAddOutcome(BlobAddOutcome);

impl BlobAddOutcome {
    /// The hash of the blob
    pub hash: Arc<Hash>,
    /// The format the blob
    pub format: BlobFormat,
    /// The size of the blob
    pub size: u64,
    /// The tag of the blob
    pub  tag: Arc<Tag>,
}
```

- [x] `BlobDownloadRequest` - interface
```
/// A request to the node to download and share the data specified by the hash.
pub struct BlobDownloadRequest(BlobDownloadRequest)
impl BlobDownloadRequest {
    /// Create a BlobDownloadRequest
    pub fn new(
        /// The hash of the data to download and share
        hash: Hash, 
        /// If the format is `BlobFormat::HashSeq`, all the children are downloaded and shared as well
        format: BlobFormat,
        /// Specifies the peer to download the data from
        peer: PeerAddr,
        /// Optional request token that can be used to authorize the download request
        token: Option<RequestToken>,
        /// Tag to tag the data with
        tag: SetTagOption,
        /// The location at which to store the data
        out: DownloadLocation) -> Self
}
```

- [x] `enum DownloadLocation` - interface
```
/// Location to store a downloaded blob at.
pub enum DownloadLocation {
    /// Store in the node's blob storage directory.
    Internal,
    /// Store at the provided path.
    External {
        /// The path to store the data at.
        path: String,
        /// If this flag is true, the data is shared in place, i.e. it is moved to the
        /// out path instead of being copied. The database itself contains only a
        /// reference to the out path of the file.
        ///
        /// If the data is modified in the location specified by the out path,
        /// download attempts for the associated hash will fail.
        in_place: bool,
    },
}

impl DownloadLocation {
    /// Store in the node's blob storage directory.
    pub fn internal() -> Self

    /// Store at the provided path.
    ///
    /// If `in_place` is true, the data is shared in place, i.e. it is moved to the
    /// out path instead of being copied. The database itself contains only a
    /// reference to the out path of the file.
    ///
    /// If the data is modified in the location specified by the out path,
    /// download attempts for the associated hash will fail.
    pub fn external(path: String, in_place: bool) -> Self
}
```

- [x] `BlobListIncompleteResponse` - interface
```
/// A response to a list blobs request
pub struct BlobListIncompleteResponse(BlobListIncompleteResponse);
impl BlobListIncompleteResponse {
    /// The size we got
    pub fn size(&self) -> u64
    /// The size we expect
    pub fn expected_size(&self) -> u64
    /// The hash of the blob
    pub fn hash(&self) -> Arc<Hash>
}
```

- [x] `BlobListCollectionsResponse` - interface
```
/// A response to a list collections request
pub struct BlobListCollectionsResponse(BlobListCollectionsResponse);
impl BlobListCollectionsResponse {
    /// Tag of the collection
    pub fn tag(&self) -> Arc<Tag>
    /// Hash of the collection
    pub fn hash(&self) -> Arc<Hash>
    /// Number of children in the collection
    ///
    /// This is optional, because the data is not always available.
    pub fn total_blobs_count(&self) -> Option<u64>
    /// Total size of the raw data referred to by all links
    ///
    /// This is optional, because the data is not always available.
    pub fn total_blobs_size(&self) -> Option<u64>
}
```

- [x] `ShareMode` - enum
```
/// Intended capability for document share tickets
pub enum ShareMode {
    /// Read-only access
    Read,
    /// Write access
    Write,
}
```

- [x] `OpenState` - interface
```
/// The state for an open replica.
pub struct OpenState(OpenState);
impl OpenState {
    /// Whether to accept sync requests for this replica.
    pub fn sync(&self) -> bool
    /// How many event subscriptions are open
    pub fn subscribers(&self) -> usize
    /// By how many handles to the doc is currently held open
    pub fn handles(&self) -> usize
}
```

- [x] `BlobFormat`
```
/// A format identifier
pub enum BlobFormat {
    /// Raw blob
    #[default]
    Raw,
    /// A sequence of BLAKE3 hashes
    HashSeq,
}
```

- [x] `PublicKey`
```
impl PublicKey {
    fn to_string(&self) -> String
    fn to_bytes(&self) -> Vec<u8>
    fn from_string(&self, str: String) -> Result<PublicKey, IrohError>
    fn from_bytes(&self, bytes: Vec<u8>) -> Result<PublicKey, IrohError>
}
```
- [x] `SocketAddr` - interface
```
/// An internet socket address, either Ipv4 or Ipv6 
enum SocketAddr {
    V4(Ipv4Addr),
    V6(Ipv6Addr),
}

/// IPv4 SocketAddr representation
pub struct Ipv4Addr(Ipv4Addr);

impl Ipv4Addr {
    /// Create a new Ipv4 addr from 4 eight-bit octets
    pub fn new(a:u8, b:u8, c:u8, d:u8) -> Self
    /// Create a new Ipv4 addr from a String
    pub fn from_string(str: String) -> Result<Self, IrohError>
    /// A string representation of an Ipv4Addr
    pub fn to_string(&self) -> String
    /// Get the 4 octets as bytes
    pub fn octets -> [u8;4]
}


/// IPv6 SocketAddr representation
pub struct Ipv6Addr(Ipv6Addr)

impl Ipv6Addr {
    /// Create a new Ipv6 addr from 8 16-bit segments
    pub fn new(a:u16, b:u16, c:u16, d:u16, e:u16, f: u16, g: u16, h: u16) -> Self
    /// Create a new Ipv6 addr from a String
    pub fn from_string(str: String) -> Result<Self, IrohError>
    /// A string representation of an Ipv6Addr
    pub fn to_string(&self) -> String
    /// Get the 8 sixteen-bit segments as an array
    pub fn segments -> [u16;8]
}

/// Type of SocketAddr
enum SocketAddrType {
    V4,
    V6
}

impl SocketAddr {
    /// The type of SocketAddr
    fn r#type(&self) -> SocketAddrType
    /// Get the IPv4 SocketAddr representation
    fn v4(&self) -> Result<Ipv4Addr, IrohError>
    /// Get the IPv6 SocketAddr representation
    fn v6(&self) -> Result<Ipv6Addr, IrohError>
}
```

- [x] `NamespaceId` - interface
```
/// The Namespace's [`PublicKey`] in bytes
pub struct NamespaceId(NamespaceId);
impl NamespaceId {
    fn to_string(&self) -> String
    fn to_bytes(&self) -> Vec<u8>
    fn from_string(&self, str: String) -> Result<NamespaceId, IrohError>
    fn from_bytes(&self, bytes: Vec<u8>) -> Result<NamespaceId, IrohError>
}
```

- [x] `DocTicket` - interface
```
/// Contains both a key (either secret or public) to a document, and a list of peers to join.
pub struct DocTicket(DocTicket);
}
impl DocTicket {
    /// Serialize the ticket to a byte array.
    pub fn to_bytes(&self) -> Result<Vec<u8>, IrohError> {

    /// Parse ticket from a byte array.
    pub fn from_bytes(bytes: Vec<u8>) -> Result<Self, IrohError>

    /// Serialize the ticket to a String
    pub fn to_string(&self) -> Result<String, IrohError>

    /// Parse the ticket from a String
    pub fn from_string(str: String) -> Result<Self, IrohError>
}
```

- [x] `AuthorId` - interface
```
/// The author's [`PublicKey`]
pub struct AuthorId(AuthorId);

impl AuthorId {
    /// Convert to byte array.
    pub fn to_bytes(&self) -> Vec<u8>

    /// Parse the AuthorId from a byte array
    pub fn from_bytes(bytes: Vec<u8> -> Result<Self, IrohError>

    /// Convert to a String
    pub fn to_string(&self) -> String

    /// Parse the AuthorID from a String
    pub fn from_string(str: String) -> Result<Self, IrohError>

    /// Convert to a base32 string limited to the first 10 bytes for a friendly string
    /// representation of the key.
    pub fn fmt_short(&self) -> String
}
```

- [x] `Tag` - interface
```
/// A tag
pub struct Tag(Tag);

impl Tag {
    /// Create a tag from a String
    pub fn from_string(str: String) -> Self

    /// Serialize a tag as a String
    pub fn to_string(&self) -> Result<String, IrohError>

    /// Create a tag from a byte array
    pub fn from_bytes(bytes: Vec<u8>) -> Self

    /// Serialize a tag as a byte array
    pub fn to_bytes(&self) -> Vec<u8>
}
```

- [x] `Hash` - interface
```
pub struct Hash(Hash);

impl Hash {
    /// Calculate the hash of the provide bytes.
    pub fn new(buf: Vec<u8>) -> Self

    /// Bytes of the hash.
    pub fn to_bytes(&self) -> Vec<u8>

    /// Create a `Hash` from its raw bytes representation.
    pub const fn from_bytes(bytes: Vec<u8>) -> Result<Self, IrohError>

    /// Get the cid as bytes.
    pub fn as_cid_bytes(&self) -> Vec<u8>

    /// Try to create a blake3 cid from cid bytes.
    ///
    /// This will only work if the prefix is the following:
    /// - version 1
    /// - raw codec
    /// - blake3 hash function
    /// - 32 byte hash size
    pub fn from_cid_bytes(bytes: Vec<u8>) -> Result<Self, IrohError>

    /// Convert the hash to a hex string.
    pub fn to_hex(&self) -> String
}

```

- [x] `Entry` - interface
```
/// A single entry in a [`Doc`]
///
/// An entry is identified by a key, its [`AuthorId`], and the [`Doc`]'s
/// [`NamespaceId`]. Its value is the 32-byte BLAKE3 [`hash`]
/// of the entry's content data, the size of this content data, and a timestamp.
pub struct Entry(Entry);

impl Entry {
    /// Get the [`NamespaceId`] of this entry.
    pub fn namespace(&self) -> NamespaceId

    /// Get the [`AuthorId`] of this entry.
    pub fn author(&self) -> AuthorId

    /// Get the key of this entry.
    pub fn key(&self) -> Vec<u8>
}
```

- [x] `GetFilter` - interface
```
/// Filter a get query onto a namespace
pub enum GetFilter {
    /// No filter, list all entries
    All,
    /// Filter for exact key match
    Key(Vec<u8>),
    /// Filter for key prefix
    Prefix(Vec<u8>),
    /// Filter by author
    Author(AuthorId),
    /// Filter by key prefix and author
    AuthorAndPrefix(AuthorId, Vec<u8>),
}

impl GetFilter {
    /// Filter by [`AuthorId`] and prefix
    pub fn author_prefix(author: AuthorId, prefix: Vec<u8>) -> Self

    /// No filter, get all entries in a namespace
    pub fn none() -> Self 

    /// Filter by [`AuthorId`]
    pub fn author(author: AuthorId) -> Self

    /// Filter by prefix
    pub fn prefix(prefix: Vec<u8>) -> Self

    /// Filter by an exact key
    pub fn key(key: Vec<u8>) -> Self 
}
```

- [x] `PeerAddr` - interface
```
/// A peer and it's addressing information.
pub struct PeerAddr(PeerAdr);

impl PeerAddr {
    /// Create a new [`PeerAddr`] with empty [`AddrInfo`].
    pub fn new(peer_id: PublicKey) -> Self

    /// Add a derp region to the peer's [`AddrInfo`].
    pub fn with_derp_region(mut self, derp_region: u16) -> Self

    /// Add the given direct addresses to the peer's [`AddrInfo`].
    pub fn with_direct_addresses(
        mut self,
        addresses: Vec<SocketAddr>,
    ) -> Self

    /// Get the direct addresses of this peer.
    pub fn direct_addresses(&self) -> Vec<SocketAddr>

    /// Get the derp region of this peer.
    pub fn derp_region(&self) -> Option<u16>
}
```

- [x] `RequestToken` - interface
```
/// A Request token is an opaque byte sequence associated with a single request.
/// Applications can use request tokens to implement request authorization,
/// user association, etc.
pub struct RequestToken(RequestToken)

impl RequestToken {
    /// Creates a new request token from bytes.
    pub fn new(bytes: Vec<u8>) -> Result<Self, IrohError>

    /// Generate a random 32 byte request token.
    pub fn generate() -> Self

    /// Returns a reference the token bytes.
    pub fn as_bytes(&self) -> Vec<u8>

    /// Create a request token from a string
    pub from_string(str: String) -> Result<Self, IrohError>

    /// Represent a request token as a string
    pub to_string(&self) -> String
}
```

### Callbacks
- [x] AddCallback / `AddProgress`
```
pub enum AddProgressType {
    Found,
    Progress,
    Done,
    AllDone,
    Abort
}

/// An AddProgress event indicating an item was found with name `name`, that can be referred to by `id`
pub struct AddProgressFound {
    /// A new unique id for this entry.
    id: u64,
    /// The name of the entry.
    name: String,
    /// The size of the entry in bytes.
    size: u64,
}

/// An AddProgress event indicating we got progress ingesting item `id`.
pub struct AddProgressProgress {
    /// The unique id of the entry.
    id: u64,
    /// The offset of the progress, in bytes.
    offset: u64,
}

/// An AddProgress event indicated we are done with `id` and now have a hash `hash`
pub struct AddProgressDone {
    /// The unique id of the entry.
    id: u64,
    /// The hash of the entry.
    hash: Hash,
}

/// An AddProgress event indicating we are done with the the whole operation
pub struct AddProgressAllDone {
    /// The hash of the created data.
    hash: Hash,
    /// The format of the added data.
    format: BlobFormat,
    /// The tag of the added data.
    tag: Tag,
}

/// An AddProgress event indicating we got an error and need to abort
pub struct AddProgressAbort(IrohError)

/// Progress updates for the add operation.
pub enum AddProgress {
    /// An item was found with name `name`, from now on referred to via `id`
    Found(AddProgressFound),
    /// We got progress ingesting item `id`.
    Progress(AddProgressProgress),
    /// We are done with `id`, and the hash is `hash`.
    Done(AddProgressDone),
    /// We are done with the whole operation.
    AllDone(AddProgressAllDone)
    /// We got an error and need to abort.
    ///
    /// This will be the last message in the stream.
    Abort(AddProgressAbort),
}

impl AddProgress {
    /// Get the type of event
    pub fn r#type(&self) -> AddProgressType
    /// Return the `AddProgressFound` event
    pub fn as_found(&self) -> Result<(), AddProgressFound>
    /// Return the `AddProgressProgress` event
    pub fn as_progress(&self) -> Result<(), AddProgressProgress>
    /// Return the `AddProgressDone` event
    pub fn as_done(&self) -> Result<(), AddProgressDone>
    /// Return the `AddAllDone`
    pub fn as_all_done(&self) -> Result<(), AddProgressAllDone>
    /// Return the `AddProgressAbort`
    pub fn as_abort(self) -> Result<(), AddProgressAbort>
}
```

- ~ValidateCallback / ValidateProgress~ `blobs.validate` is not yet implemented in core
- [x] SubscribeCallback / LiveEvent
- [x] DownloadCallback / DownloadProgress

**Comment by dignifiedquire** [comment]
@ramfox can we close this?

**Comment by ramfox** [comment]
yes!
